
name: Terraform Execution

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Storing manifests in GitHub
      uses: actions/upload-artifact@v3
      with:
       name: terraformArtifacts
       path: terraform/*
        
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Downloading manifests from GitHub
      uses: actions/download-artifact@v3
      with:
       name: terraformArtifacts

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: 'ASIA4KGSLQY3MTHUMLND'
        aws-secret-access-key: 'QTb14wcKG2ac6p6Y0nZiM+i3igp0H1U+lDT/9wsQ'
        aws-session-token: 'FwoGZXIvYXdzEKT//////////wEaDIGEkYeEvYSc0zpbryK5ATiXEZj8K9AuTqwdrNC4mcZzVCQ+eS2bxCXpdsVe92qHLohM2seAbe51xNetZx+rFLqAu/HrLhU44JIm0K5YHnC3ZIgdm173hYRQyBBe4lzTs5YrmtQ5edkI2aEMwUg4bF7LC0qEuX4oBMDeCiJaFdxOH24DcafD2fsHXX9Dp8lY95EEnusnKVMJ+qrGHc61Sb4IENs3MY+e1wvLfiJxvsjYcOJoeIIQoKocrdaMqLyl92hF2Kqv87/2KMmM0KgGMi3EkSahcCkD5qlUxg5FkqkxahFmT9OMONZ0/AeepTOddYtHiVEW4GS7t5jLkkg='

    
    - name: Validate AWS Credentials working or not
      run: |
        aws sts get-caller-identity

    - name: Restore cached Primes
      id: cache-primes-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          terraform.tfstate*
        key: ${{ runner.os }}-state
        
    - name: Execute terraform scripts to launch S3 bucket
      run: |
        terraform init
        terraform apply --auto-approve
        
    - name: Cache state files
      id: cache-state
      uses: actions/cache@v3
      with:
        path: |
          terraform.tfstate*
        key: ${{ runner.os }}-state        
        
